#!/bin/bash
mkdir -p testbench/testcases


for f in $1/*.s
 do 
 	fname=$(basename "$f" .s)
 	make "$1/$fname.mips.bin" -B
 	cp "$1/$fname.mips.gld" testbench/testcases
 	cp "$1/$fname.mips.bin" testbench/testcases
 	rm "$1/$fname.mips.bin"
 done

